export const BlogActions = {
  blogs: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    DATA_EDITED: "BLOG_DATA_EDITED",
    BLOG_DELETED: "BLOG_DATA_DELETED",
    BLOG_LIKED: "BLOG_LIKED",
    BLOG_COMMENTED: "BLOG_COMMENTED",
  },
};
